name: r2techture
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  io: ^1.0.5
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
